// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'es-ES'],
  firebaseConfig: {
    apiKey: 'AIzaSyDdG6B2oYfSSDxutp1D9NNa-kkKswHPw8g',
    authDomain: 'test-89a00.firebaseapp.com',
    projectId: 'test-89a00',
    storageBucket: 'test-89a00.appspot.com',
    messagingSenderId: '739684870971',
    appId: '1:739684870971:web:dc404978c2afae43f3251e',
    measurementId: 'G-627Z7J2MJ3',
  },
};
